version: '3'
services:
  colissithon:
    build:
      context: ./context/
    ports:
    - "9876:9876"
    environment:
      COLISSITHON_NAME: COLISSITHON
    networks:
    - insight
networks:
  insight:
