version: '3'
services:
    colissithon:
        build:
            context: ./context/
        image: reachhubcorp/colissithon:latest
        container_name: colissithon
        ports:
            - "9876:9876"
        environment:
            - INSIGHT_IP=192.168.0.30
            - INSIGHT_PORT=8080
            - KAFKA_IP=192.168.0.50
            - KAFKA_PORT=8092
            - COLISSITHON_PORT=9876
            - FROM_TRAVELTHON=travelthon_out
            - FROM_COMPARATHON=comparathon_out
            - FROM_TWEETHON=tweethon_out
            - DEBUG_LEVEL=INFO
        networks:
        - reach
networks:
    reach : 
        external: true
