version: '3'
services:
    colissithon:
        build:
            context: ./context/
        image: reachhubcorp/colissithon:latest
        container_name: colissithon
        ports:
            - "9876:9876"
        environment:
            - INSIGHT_IP=192.168.0.30
            - INSIGHT_PORT=8080
            - KAFKA_IP=192.168.0.40
            - KAFKA_PORT=8092
            - COLISSITHON_PORT=9876
            - FROM_TRAVELTHON=travelthon
            - FROM_COMPARATHON=comparathon
            - FROM_TWEETHON=tweethon
            - DEBUG_LEVEL=INFO