version: '3'
services:
    colissithon:
        build:
            context: ./context/
        image: reachhubcorp/colissithon:latest
        container_name: colissithon
        ports:
        - "9876:9876"
        environment:
          INSIGHT_IP: "${ipinsight}"
          INSIGHT_PORT: 8080
          KAFKA_IP: "${ipkafka}"
          KAFKA_PORT: 8092
          COLISSITHON_PORT: 9876
          FROM_TRAVELTHON: locToColissi
          FROM_COMPARATHON: ggimgToColissi
          FROM_TWEETHON: tweetToColissi
          FROM_CROUSTIBATCH: mediaToColissi
          DEBUG_LEVEL: INFO
